// GENERATED by scripts/check_room_policy.py --sync from tactical/policy/*.json. Do not edit.
export default {
 "rmc14": {
  "assets": [
   {
    "count": 1,
    "owner": "mortar",
    "type": "mortar"
   }
  ],
  "enemy": {
   "color": "#ff5a5a",
   "marker": "triangle"
  },
  "fork": "rmc14",
  "functions": [],
  "layers": {
   "assets": {
    "write": [
     "service",
     "staff"
    ]
   },
   "requests": {
    "write": [
     "staff",
     "service"
    ]
   },
   "service": {
    "write": [
     "service"
    ]
   },
   "shared": {
    "cadenceSec": 0,
    "write": [
     "staff"
    ]
   },
   "squad:*": {
    "write": [
     "squad"
    ]
   },
   "staff": {
    "write": [
     "staff"
    ]
   }
  },
  "levels": {
   "observer": {
    "color": "#8a99b3",
    "line": null,
    "marker": null,
    "nameEn": "Observer",
    "nameRu": "Наблюдатель"
   },
   "service": {
    "color": "#5ad1e6",
    "line": {
     "dash": [
      6,
      4
     ],
     "width": 2
    },
    "marker": "circle",
    "nameEn": "Service",
    "nameRu": "Служба"
   },
   "squad": {
    "color": "squad",
    "line": {
     "dash": [],
     "width": 2.5
    },
    "marker": "diamond",
    "nameEn": "Squad",
    "nameRu": "Отряд"
   },
   "staff": {
    "color": "#f5f5f5",
    "line": {
     "dash": [],
     "width": 4
    },
    "marker": "square",
    "nameEn": "Staff",
    "nameRu": "Штаб"
   }
  },
  "limits": {
   "bytes": 2097152,
   "callsign": 20,
   "label": 40,
   "message": 4096,
   "note": 80,
   "objects": 2000,
   "opsPerMin": 60,
   "opsPerSec": 10,
   "points": 64
  },
  "posts": [
   {
    "admin": true,
    "id": "so",
    "level": "staff",
    "max": 3,
    "nameEn": "Staff Officer",
    "nameRu": "Офицер штаба"
   },
   {
    "id": "mortar",
    "level": "service",
    "max": 2,
    "nameEn": "Mortar crew",
    "nameRu": "Миномётный расчёт"
   },
   {
    "id": "observer",
    "level": "observer",
    "max": 8,
    "nameEn": "Observer",
    "nameRu": "Наблюдатель"
   }
  ],
  "rights": {
   "acceptRequest": [
    "asset-owner",
    "staff"
   ],
   "assignLabel": [
    "staff"
   ],
   "confirmJoin": [
    "staff",
    "service"
   ],
   "extend": [
    "staff"
   ],
   "kick": [
    "staff"
   ],
   "publishCalibration": [
    "staff",
    "service"
   ],
   "radioSilence": [
    "staff"
   ]
  },
  "sanction": [
   {
    "server": "[EN][MRP] Rounys Marine Corps Alamo [US East]",
    "since": null,
    "status": "none"
   }
  ],
  "squads": {},
  "stage": "so-mortar",
  "ttl": {
   "enemyMarkerSec": 600,
   "exportGraceSec": 3600,
   "memberIdleSec": 600,
   "roomExtendSec": 3600,
   "roomIdleLockSec": 480,
   "roomMaxSec": 10800,
   "wordSec": 300
  },
  "v": 1
 },
 "stories_cm": {
  "assets": [
   {
    "count": 1,
    "owner": "mortar",
    "type": "mortar"
   }
  ],
  "enemy": {
   "color": "#ff5a5a",
   "marker": "triangle"
  },
  "fork": "stories_cm",
  "functions": [],
  "layers": {
   "assets": {
    "write": [
     "service",
     "staff"
    ]
   },
   "requests": {
    "write": [
     "staff",
     "service"
    ]
   },
   "service": {
    "write": [
     "service"
    ]
   },
   "shared": {
    "cadenceSec": 0,
    "write": [
     "staff"
    ]
   },
   "squad:*": {
    "write": [
     "squad"
    ]
   },
   "staff": {
    "write": [
     "staff"
    ]
   }
  },
  "levels": {
   "observer": {
    "color": "#8a99b3",
    "line": null,
    "marker": null,
    "nameEn": "Observer",
    "nameRu": "Наблюдатель"
   },
   "service": {
    "color": "#5ad1e6",
    "line": {
     "dash": [
      6,
      4
     ],
     "width": 2
    },
    "marker": "circle",
    "nameEn": "Service",
    "nameRu": "Служба"
   },
   "squad": {
    "color": "squad",
    "line": {
     "dash": [],
     "width": 2.5
    },
    "marker": "diamond",
    "nameEn": "Squad",
    "nameRu": "Отряд"
   },
   "staff": {
    "color": "#f5f5f5",
    "line": {
     "dash": [],
     "width": 4
    },
    "marker": "square",
    "nameEn": "Staff",
    "nameRu": "Штаб"
   }
  },
  "limits": {
   "bytes": 2097152,
   "callsign": 20,
   "label": 40,
   "message": 4096,
   "note": 80,
   "objects": 2000,
   "opsPerMin": 60,
   "opsPerSec": 10,
   "points": 64
  },
  "posts": [
   {
    "admin": true,
    "id": "so",
    "level": "staff",
    "max": 3,
    "nameEn": "Staff Officer",
    "nameRu": "Офицер штаба"
   },
   {
    "id": "mortar",
    "level": "service",
    "max": 2,
    "nameEn": "Mortar crew",
    "nameRu": "Миномётный расчёт"
   },
   {
    "id": "observer",
    "level": "observer",
    "max": 8,
    "nameEn": "Observer",
    "nameRu": "Наблюдатель"
   }
  ],
  "rights": {
   "acceptRequest": [
    "asset-owner",
    "staff"
   ],
   "assignLabel": [
    "staff"
   ],
   "confirmJoin": [
    "staff",
    "service"
   ],
   "extend": [
    "staff"
   ],
   "kick": [
    "staff"
   ],
   "publishCalibration": [
    "staff",
    "service"
   ],
   "radioSilence": [
    "staff"
   ]
  },
  "sanction": [
   {
    "server": "Space Stories - Marine Corps Core",
    "since": null,
    "status": "none"
   }
  ],
  "squads": {},
  "stage": "so-mortar",
  "ttl": {
   "enemyMarkerSec": 600,
   "exportGraceSec": 3600,
   "memberIdleSec": 600,
   "roomExtendSec": 3600,
   "roomIdleLockSec": 480,
   "roomMaxSec": 10800,
   "wordSec": 300
  },
  "v": 1
 }
};
