# scripts/check_room_policy.py — validates tactical/policy/*.json against the room contract.
# Run: python scripts/check_room_policy.py   (exit 1 on any problem)
import json, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
LEVELS = {'staff', 'squad', 'service', 'observer'}
MARKERS = {'square', 'diamond', 'circle', None}
LAYER_KEYS = {'shared', 'staff', 'squad:*', 'service', 'requests', 'assets'}
RIGHTS = {'confirmJoin', 'publishCalibration', 'acceptRequest', 'kick', 'assignLabel', 'radioSilence', 'extend'}
TTL = {'enemyMarkerSec', 'roomMaxSec', 'roomExtendSec', 'roomIdleLockSec', 'exportGraceSec', 'memberIdleSec', 'wordSec'}
LIMITS = {'objects', 'label', 'note', 'callsign', 'points', 'opsPerSec', 'opsPerMin', 'bytes', 'message'}
ASSET_TYPES = {'mortar', 'ob', 'dropship', 'supply', 'medevac'}

def fail(msg):
    print('FAIL', msg); sys.exit(1)

def pos_int(v):
    return type(v) is int and v > 0

def _check(path):
    p = json.loads(path.read_text(encoding='utf-8-sig'))
    if p.get('v') != 1: fail(f'{path.name}: v must be 1')
    if p.get('fork') != path.stem: fail(f'{path.name}: fork must equal file stem')
    for s in p['sanction']:
        if s['status'] not in ('none', 'pilot', 'approved'): fail(f'{path.name}: sanction status {s["status"]}')
    if set(p['levels']) != LEVELS: fail(f'{path.name}: levels {set(p["levels"])}')
    for k, lv in p['levels'].items():
        if lv.get('marker') not in MARKERS: fail(f'{path.name}: level {k} marker')
    ids = [x['id'] for x in p['posts']]
    if len(ids) != len(set(ids)): fail(f'{path.name}: duplicate post ids')
    has_staff = False
    for post in p['posts']:
        if post['level'] not in LEVELS: fail(f'{path.name}: post {post["id"]} level')
        if post['level'] == 'squad' and not post.get('perSquad'): fail(f'{path.name}: squad post {post["id"]} needs perSquad')
        if not pos_int(post.get('max')): fail(f'{path.name}: post {post["id"]} max must be a positive integer')
        if post['level'] == 'staff': has_staff = True
    if not has_staff: fail(f'{path.name}: no staff post')
    if set(p['layers']) != LAYER_KEYS: fail(f'{path.name}: layers {set(p["layers"])}')
    for k, layer in p['layers'].items():
        if not set(layer['write']) <= LEVELS: fail(f'{path.name}: layer {k} write')
    if set(p['rights']) != RIGHTS: fail(f'{path.name}: rights {set(p["rights"]) ^ RIGHTS}')
    for k, v in p['rights'].items():
        if not isinstance(v, list) or not set(v) <= (LEVELS | {'asset-owner'}): fail(f'{path.name}: rights {k} {v}')
    if set(p['ttl']) != TTL: fail(f'{path.name}: ttl {set(p["ttl"]) ^ TTL}')
    for k, v in p['ttl'].items():
        if not pos_int(v): fail(f'{path.name}: ttl {k} must be a positive integer')
    if set(p['limits']) != LIMITS: fail(f'{path.name}: limits {set(p["limits"]) ^ LIMITS}')
    for k, v in p['limits'].items():
        if not pos_int(v): fail(f'{path.name}: limits {k} must be a positive integer')
    asset_types_seen = set()
    for a in p['assets']:
        if a['type'] not in ASSET_TYPES: fail(f'{path.name}: asset type {a["type"]}')
        if a['type'] in asset_types_seen: fail(f'{path.name}: duplicate asset type {a["type"]}')
        asset_types_seen.add(a['type'])
        if a['owner'] not in ids: fail(f'{path.name}: asset owner {a["owner"]} is not a post')
        owner_post = next(x for x in p['posts'] if x['id'] == a['owner'])
        if owner_post['level'] == 'observer': fail(f'{path.name}: asset owner {a["owner"]} is an observer post')
        if 'count' in a and not pos_int(a['count']): fail(f'{path.name}: asset {a["type"]} count must be a positive integer')
        if 'loader' in a and a['loader'] not in ids: fail(f'{path.name}: asset {a["type"]} loader {a["loader"]} is not a post')
    for f in p['functions']:
        if not isinstance(f.get('id'), str) or not f.get('nameRu'): fail(f'{path.name}: function {f}')
    for sq in p['squads'].values():
        if not sq['color'].startswith('#') or len(sq['color']) != 7: fail(f'{path.name}: squad colour {sq}')
    print('ok', path.name, len(p['posts']), 'posts', len(p['assets']), 'assets')

def check(path):
    try:
        _check(path)
    except (KeyError, TypeError, AttributeError, ValueError) as e:
        fail(f'{path.name}: {type(e).__name__} {e}')

files = sorted((ROOT / 'tactical' / 'policy').glob('*.json'))
if not files: fail('no policy files')
for f in files: check(f)

# worker/room/policies.js is generated from these files so the Worker and the
# page read one source. `--sync` writes it; the default run fails when stale.
bundle = {f.stem: json.loads(f.read_text(encoding='utf-8-sig')) for f in files}
generated = ('// GENERATED by scripts/check_room_policy.py --sync from tactical/policy/*.json. Do not edit.\n'
             'export default ' + json.dumps(bundle, ensure_ascii=False, indent=1, sort_keys=True) + ';\n')
target = ROOT / 'worker' / 'room' / 'policies.js'
if '--sync' in sys.argv:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generated, encoding='utf-8', newline='\n')
    print('wrote', target.relative_to(ROOT))
elif not target.exists() or target.read_text(encoding='utf-8') != generated:
    fail('worker/room/policies.js is stale: run python scripts/check_room_policy.py --sync')
print('OK')
